### ISSUE TITLE
setup.py

### ISSUE THREAD

**Issue by he-lourenco** [pimoroni/drv2605-python#4]
Hi there, I am using cmd line to install this package but the following error is coming up... Not sure if it's a problem with my machine or with the library, but any help would be very much appreciated.

`Collecting drv2605
  Using cached drv2605-0.0.3-py3-none-any.whl (6.1 kB)
Collecting i2cdevice>=0.0.6
  Using cached i2cdevice-0.0.7-py3-none-any.whl (7.2 kB)
Collecting smbus
  Using cached smbus-1.1.post2.tar.gz (104 kB)
Using legacy 'setup.py install' for smbus, since package 'wheel' is not installed.
Installing collected packages: smbus, i2cdevice, drv2605
    Running setup.py install for smbus ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\hlourenco\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\hlourenco\\AppData\\Local\\Temp\\pip-install-rcqzjfpx\\smbus_a5820db61de0469da9d466705d6c3b93\\setup.py'"'"'; __file__='"'"'C:\\Users\\hlourenco\\AppData\\Local\\Temp\\pip-install-rcqzjfpx\\smbus_a5820db61de0469da9d466705d6c3b93\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\hlourenco\AppData\Local\Temp\pip-record-u9ivozfs\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\hlourenco\appdata\local\programs\python\python39\Include\smbus'
         cwd: C:\Users\hlourenco\AppData\Local\Temp\pip-install-rcqzjfpx\smbus_a5820db61de0469da9d466705d6c3b93\
    Complete output (5 lines):
    running install
    running build
    running build_ext
    error: [WinError 2] The system cannot find the file specified
    building 'i2c' library
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\hlourenco\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\hlourenco\\AppData\\Local\\Temp\\pip-install-rcqzjfpx\\smbus_a5820db61de0469da9d466705d6c3b93\\setup.py'"'"'; __file__='"'"'C:\\Users\\hlourenco\\AppData\\Local\\Temp\\pip-install-rcqzjfpx\\smbus_a5820db61de0469da9d466705d6c3b93\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\hlourenco\AppData\Local\Temp\pip-record-u9ivozfs\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\hlourenco\appdata\local\programs\python\python39\Include\smbus' Check the logs for full command output.`

**Comment by szabomFB** [comment]
I'm seeing the same error- were you able to resolve in any way?

**Comment by Gadgetoid** [comment]
The crucial issue is: `Using legacy 'setup.py install' for smbus, since package 'wheel' is not installed.`

It's falling back to trying to compile the `smbus` package from source because it can't install a pre-compiled .whl file.

Since wheel is almost essential on the Pi, I'd consider this a broken Python installation. What OS are you running?

In any case, the fix is your distro-equivilent version of `sudo apt install python3-wheel` or just `sudo python3 -m pip install wheel`

**Comment by szabomFB** [comment]
Yes, I did try installing wheel and also tried on another computer with python 3.8 and ran into same issue. Could the newer version number be the source of the problem?

Here is the error message with wheel installed:

Collecting i2cdevice>=0.0.6
  Using cached i2cdevice-0.0.7-py3-none-any.whl (7.2 kB)
Building wheels for collected packages: smbus
  Building wheel for smbus (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Python38\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\szabom\\AppData\\Local\\Temp\\pip-install-0mv8vf2z\\smbus_ed93ab9e55914f66aa2e77adb3cdbfb5\\setup.py'"'"'; __file__='"'"'C:\\Users\\szabom\\AppData\\Local\\Temp\\pip-install-0mv8vf2z\\smbus_ed93ab9e55914f66aa2e77adb3cdbfb5\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\szabom\AppData\Local\Temp\pip-wheel-8yyq7205'
       cwd: C:\Users\szabom\AppData\Local\Temp\pip-install-0mv8vf2z\smbus_ed93ab9e55914f66aa2e77adb3cdbfb5\
  Complete output (5 lines):
  running bdist_wheel
  running build
  running build_ext
  error: [WinError 2] The system cannot find the file specified
  building 'i2c' library

  ERROR: Failed building wheel for smbus
  Running setup.py clean for smbus
Failed to build smbus

**Comment by Gadgetoid** [comment]
Ah there's no Python 3.8 wheel for smbus, which doesn't help - https://www.piwheels.org/project/smbus/

Installing `python3-dev` or otherwise installing development headers for your Python version should get it building from source.
